# Generated by Django 4.0.3 on 2022-03-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folio_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('tagline', models.CharField(blank=True, max_length=80, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('current_project_link', models.URLField(blank=True, null=True)),
                ('current_project_desc', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_github_profile', models.URLField(blank=True, null=True)),
                ('contact_linkedin_profile', models.URLField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folio_account.useraccount')),
            ],
        ),
    ]
