# Generated by Django 4.0.3 on 2022-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
