# Generated by Django 4.0.3 on 2022-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='about_me',
        ),
        migrations.AddField(
            model_name='folio',
            name='future_goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
