# Generated by Django 4.0.3 on 2022-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0006_remove_folio_about_me_folio_future_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
