# Generated by Django 4.0.3 on 2022-05-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0008_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folio',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='contact_github_profile',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='contact_linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='contact_number',
        ),
    ]
