# Generated by Django 4.0.3 on 2022-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='number_of_licenses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
