# Generated by Django 4.0.3 on 2022-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio_account', '0003_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='default_phone_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
