# Generated by Django 4.0.3 on 2022-04-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_full_name', models.CharField(max_length=40)),
                ('purchaser_email', models.EmailField(max_length=254)),
                ('purchaser_phone_number', models.CharField(max_length=20)),
                ('purchaser_street_address1', models.CharField(max_length=80)),
                ('purchaser_street_address2', models.CharField(max_length=80)),
                ('purchaser_town_or_city', models.CharField(max_length=40)),
                ('purchaser_postcode', models.CharField(max_length=20)),
                ('purchaser_county', models.CharField(max_length=20)),
                ('purchaser_country', django_countries.fields.CountryField(max_length=2)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('no_of_licenses_purchased', models.PositiveSmallIntegerField(default=0)),
                ('purchase_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
