# Generated by Django 4.0.3 on 2022-04-18 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepurchase',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
